### ISSUE TITLE
Problem add_module

### ISSUE THREAD

**Issue by lucascorrea** [heartcombo/devise-encryptable#16]
I'm with a problem to use this gem, could anyone help me?

```
/Users/lucas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'devise-encryptable'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `add_module' for Devise:Module
Backtrace for gem load error is:
/Users/lucas/.rbenv/versions/2.3.1/gemsets/icom/gems/devise-encryptable-0.2.0/lib/devise/encryptable/encryptable.rb:28:in `<top (required)>'
/Users/lucas/.rbenv/versions/2.3.1/gemsets/icom/gems/devise-encryptable-0.2.0/lib/devise-encryptable.rb:1:in `require'
/Users/lucas/.rbenv/versions/2.3.1/gemsets/icom/gems/devise-encryptable-0.2.0/lib/devise-encryptable.rb:1:in `<top (required)>'
/Users/lucas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/Users/lucas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in
```

**Comment by jontarg** [comment]
Be sure to have `gem 'devise-encryptable'` **after** `gem 'devise'` or the gem that uses devise.

**Comment by dportalesr** [comment]
I know I'm late but make sure to have `gem 'devise-encryptable'` **after** `gem 'devise'` or the gem that uses devise.
